### ISSUE TITLE
[COMUM - BACK] lista de chamados

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-requests#1]
🚀 Registro de chamados
---
O cliente deseja cadastro de chamados para acompanhamento dos problemas levantados e suas respectivas soluções, para que, a partir de uma base de dados estabelecida, consiga evitar retrabalhos e consultar soluções cujo resultado foi verificado. 
>💡 Esta tarefa se refere à listagem de chamados abertos por um usuário comum específico

#### Expectativa de finalização
Microsserviço criado com funcionalidade de listagem de chamados abertos por um determinado usuário comum, onde, a partir do envio de uma informação identificadora do usuário (como um id), seja retornado a respectiva lista de chamados.

> Informações adicionais: **utilizar Java, respeitando os conceitos de SOLID e RESTful**

#### Solução proposta
- [x] Criação de funcionalidade para filtragem dos chamados a partir do usuário que abriu o chamado (ou o retorno de um campo específico do documento de "usuário" chamado "chamados")
<div align="center">

| VERBO                                           | ROTA                                    | AÇÃO                             |
|:----------------------------------------------|:--------------------------------------|:---------------------------------|
|  [![image](https://img.shields.io/badge/GET-2E8B57?style=for-the-badge)]()  | `/requests/users/{id}` | obtenção dos chamados de determinado usuário |
</div>

---
#### Espaço para anotações do responsável pela tarefa
...

#### Capturas de tela (caso de tarefa com alteração no layout)
...

---
#### Definition of Done
- [ ] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by CaioVitorDias1** [comment]
<h2>Documentação<h2>

<h3>Criação da Query utilizada para captar todos os chamados de um usuário:<h3>

![image](https://user-images.githubusercontent.com/79228873/163077441-e1e92088-dc1f-48d3-bab5-fd2311efb6fa.png)

<h3>Foi elaborada a lógica para guardar os chamados de um usuário em específico<h3>

![image](https://user-images.githubusercontent.com/79228873/163077376-c7b4d9d1-718c-4ae4-8d75-7dff8cae29f5.png)

<h3>Foi feita a configuração da rota que será utilizada para pegar os chamados pelo id:<h3>

![image](https://user-images.githubusercontent.com/79228873/163077487-af537608-f719-4505-8c5e-21636d8b66f7.png)
