### ISSUE TITLE
[DISCOVERY] Pesquisa sobre FAQ

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-requests#12]

**Comment by Nepoun** [comment]
Resultado das pesquisas feitas sobre FAQ

### Definição de FAQ

De acordo com alguns sites que li diz que FAQ é a sigla para Frequently Asked Questions, é uma pagina onde tem um resumo das perguntas mais frequentes do usuário e suas respostas de forma mais genérica, servindo para que os consumidores possam solucionar suas proprias questões sem que precise de alguém do suporte para atende-los.

Alguns exemplos de perguntas frequentes:


“Onde posso encontrar respostas para duvidas comuns de funcionamento?”
“Como posso resolver problemas com cartão de crédito?”
“Como posso atualizar minha assinatura?”
“Como alterar minha senha”
“Erro ??? sempre que entro, o que fazer?”

Em geral são perguntas mais genéricas que também possuiriam respostas genéricas e funcionais, um FAQ ajudaria a ter mais eficiência nisso
---
De acordo com um dos sites que encontrei falando sobre o assunto, foi dito que um bom FAQ precisa passar por esses dez passos para ser criado:
<h4>
1. Considere as características do seu produto/serviço <br/>
2. Levante as dúvidas mais recorrentes<br/>
3. Agrupe as principais perguntas<br/>
4. Crie respostas objetivas<br/>
5. Use imagens e prints<br/>
6. Inclua links para conteúdos relacionados <br/>
7. Dê oportunidade para seus clientes enviarem sugestões<br/>
8. Revise sua página de FAQ frequentemente<br/>
9. Deixe sua página de FAQ visível e acessível<br/>
10. Mantenha todas as perguntas e respostas organizadas<br/>
11. [Bônus] Lembre-se de disponibilizar canais de atendimento direto<br/>
</h4>

---

O primeiro passo nosso é analisar melhor o que desenvolvermos e tentar identificar quais seriam duvidas mais básicas, como como acessar algo, alterar senhas, fazer chamadas, verificar dados, coisas assim
Depois de analisarmos bem esse aspecto seria bom agrupar as perguntas principais em temas. Como por exemplo uma categoria só com duvidas envolvendo a própria conta, depois outra com duvidas de como criar chamadas, outra em como resolver coisas relacionadas a cobrança. Duvidas do gênero. Dentro dessas categorias também teriam perguntas mais especificas, então seria necessário estudarmos e descobrir quais seriam as principais duvidas e coloca-las em categorias

Quando feito, precisaríamos criar respostas objetivas para cada uma das perguntas pensadas, de preferencia utilizando links e/ou fotos mostrando melhor como se feito. Mas precisa ser bem objetivo.

Seria ótimo também se houvessem formas do cliente, mesmo depois de ver o FAQ, enviar perguntas e/ou sugestões nisso

Com o desenvolvimento das sprints, seria necessário que sempre fosse revisado o site para decidir se há mais coisas que devam ser colocadas no FAQ ou se caso algo tenha se tornado desnecessário 

Agora na parte mais técnica, precisaríamos criar uma pagina que pode ser cadastrada (teríamos de ver quem poderia alterar isso também e como seria feito) livremente para poder alterar quaisquer coisas que achem necessário, também para facilitar nosso trabalho de atualizar esse FAQ como também tornar o código mais dinâmico
