### ISSUE TITLE
[DISCOVERY] Pesquisa sobre análise de causa raíz

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-requests#13]

**Comment by CaioVitorDias1** [comment]
<h1>Pesquisa inicial sobre análise de causa raiz 📈 :<h1> 

<h4>Análise de causa raiz é basicamente uma série de metodologias elaboradas com o intuito de tratar ou descobrir a causa principal de determinado problema, baseando-se na quantidade de informação adquirida sobre o problema, quanto mais, melhor.<h4>

<h1>:computer: Possíveis aplicabilidades ao projeto:<h1>

<h2> ✒️ Análise de Dados "Manual"<h2>

<h4>Teoricamente,  uma maneira simples de aplicar esse conceito ao projeto seria através de um input manual de dados pelo próprio Suporte.<h4>

<h3>O fluxo seria mais ou menos assim:<h3>

<h4>O Suporte possuiria uma "tela de análise de causa raiz", na qual o mesmo registraria os problemas parecidos com nomes padronizados, assim, dentro desse problema, haveriam suas consequências diversas, e o Suporte registraria cada uma delas com um nome padronizado também. Por fim, após padronizar os problemas e suas consequências, ele designaria o que acreditaria ser o motivo raiz do problema.
Haveria também uma "tela de dicionário de soluções", que possuiria todos os registros realizados pelo Suporte, na qual ele  poderia procurar e filtrar pelos problemas repetidos para encontrar a causa raiz já registrada, facilitando assim o fluxo de trabalho.<h4>
<h3>Exemplo: <h3>

![image](https://user-images.githubusercontent.com/79228873/163493750-053367c9-73d0-42ba-bd1f-fe0976cff0f6.png)

<h2> 📉 Análise de Dados<h2>

<h4>Teoricamente, também é possível utilizar da análise de dados de maneira bruta (dados numéricos) através de algo parecido com uma Análise de Componentes Principais (ACP). 
Para tal análise seria necessário uma "indexação" dos problemas e suas soluções, para que assim, um Dado Real (situação) possa ser transformado em um Dado Numérico. Exemplo: Problema de conexão = 1, Falta de peças x = 15. 
A partir disso, seria coletado também informações adicionais como: a quantidade de chamados com soluções aprovadas e reprovadas, quantidade de chamados ainda em andamento/espera e etc. 
Com uma quantidade suficiente de dados coletados seria possível formular uma análise de dados, utilizando de alguma metodologia.<h4>

<h2> 📊 Possíveis metodologias para análise de dados: <h2>

<h3>Diagrama T-score Plot<h3>

![image](https://user-images.githubusercontent.com/79228873/163488352-368412a0-bd42-4073-a926-739b1fcb14d0.png)
<h4>(Exemplo de plotagem do diagrama T-score)<h4>

<h4>Através deste diagrama é possível observar irregularidades de acordo com o distanciamento de pontos.<h4>

<h3>Diagrama Hotelling T2 Plot<h3>

![image](https://user-images.githubusercontent.com/79228873/163488556-b19e85cd-0fe3-47be-9c65-0cc2a07ddda6.png)
<h4>(Exemplo de plotagem do diagrama Hotelling T2)<h4>

<h4>Através deste diagrama é possível observar irregularidades de acordo com a altura dos picos.<h4>

<h3>Diagrama Loadings Plot<h3>

![image](https://user-images.githubusercontent.com/79228873/163489732-467fd005-abac-4d85-98f2-762bc94eb160.png)
<h4>(Exemplo de plotagem do diagrama Loadings)<h4>

<h4>Parecido com o T-score, através de gráfico é possível observar irregularidades de acordo com o distanciamento dos pontos.<h4>

<h2>Conclusão 📝 <h2>

<h4>Embora a aplicabilidade da Análise de Causa Raiz ao projeto ainda é muito abstrata, já é possível teorizar algumas ideias. Talvez seja viável empregar esse conceito utilizando de simples inputs do Suporte de forma a gerar uma base de dados para futuras consultas de resoluções de problemas. Ou então, utilizar da análise de dados cru com a transformação de Dados Reais em Dados Numéricos seja o caminho mais vantajoso. Ou até mesmo,  juntar os dois processos, com o Suporte fazendo o input de dados e carregando uma base de dados de resolução, à medida que, esses dados padronizados fossem sendo transformados em Dados Numéricos, para que posteriormente sejam analisados.<h4>

<h3>Independente de qualquer coisa, ainda restam muitas dúvidas:<h3>

<h4>- Que linguagens, bibliotecas e frameworks utilizar para cada processo?<h4>
<h4>- Qual processo seria mais interessante? <h4>
<h4>- Seria realmente possível a implementação desses processos?<h4>
<h4>- Seria possível e viável implementar os dois processos ao mesmo tempo?<h4>
<h4>- Quais outros processos poderiam ser úteis?<h4>
<h4>- Qual o nível de dificuldade de implementação de cada processo?<h4>

<h2>Principais Referências Utilizadas:<h2>

Artigo 1: https://parthprasoon123.medium.com/root-cause-analysis-for-process-manufacturing-industry-e6b77a0e9b9d 

Artigo 2: https://ocefpaf.github.io/python4oceanographers/blog/2014/12/01/PCA/
