### ISSUE TITLE
[CHAMADOS - BACK] Solução de chamado

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-requests#16]

**Comment by GabrielCamargoL** [comment]
<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante a integração do mongoDB e Spring: Java 11, Spring 2.6.6, OpenFeign 3.1.2, MongoDB, VS Code.

Adicionei essa dependencia do spring cloud e open feign para acessar metodos do microsserviço de soluções (https://github.com/The-Bugger-Ducks/help-duck-solution-center).

> arquivo: pom.xml
![image](https://user-images.githubusercontent.com/55204419/168098234-3306f0a9-88e9-4b27-924c-647097903636.png)

primeiramente, ativar a configuração para o Feign funcionar, colocando a anotação @EnableFeignClients no main.

![image](https://user-images.githubusercontent.com/55204419/168099520-15b51505-91ad-468d-b2a3-bb53f169b4d0.png)


A print a seguir mostra como foi feito para requisitar solução de um chamado para compor a pagina "detalhes do chamado"

> arquivo: /interfaces/SolutionRequest.java
![image](https://user-images.githubusercontent.com/55204419/168098875-fa58fdfe-bf0c-4399-ac51-6f54d152fdf4.png)

> {url.solutions} está indicado em cada ambiente de application (dev/prod)

> arquivo: application-dev.properties
![image](https://user-images.githubusercontent.com/55204419/168099176-5b055397-ac49-4a1b-92a4-f04d48bd6e28.png)

> arquivo: application-prod.properties
![image](https://user-images.githubusercontent.com/55204419/168099222-1a948d3e-f924-4a48-a8b1-1a84e991ed94.png)


<br>

Implementando a requisição para o microsserviço de soluções para o chamado se o chamado existir. Caso exista uma solução para o tal chamado, temos um try catch tratando isso, aplicando um setSolution com body em Tickets. Caso não, aplica-se null para a solução.

> Implementação da interface em TicketServices.java
![image](https://user-images.githubusercontent.com/55204419/168100753-280290b7-d1fd-4f1a-aa02-79925aa34edd.png)





### 📸 Prints da collection do cluster do mongodb criado pelo Spring:

Requisição de chamado COM solução:

![image](https://user-images.githubusercontent.com/55204419/168099685-0009c4d2-b6ea-4ee4-b5a0-d41e50a0bd9e.png)

Requisição de chamado SEM solução:

![image](https://user-images.githubusercontent.com/55204419/168099811-b9ad5c14-7089-4c2e-a40d-d03c922e97dc.png)
