### ISSUE TITLE
[BACK] Linkar equipamento no chamado

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-requests#20]

**Comment by GabrielCamargoL** [comment]
<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante a integração do mongoDB e Spring: Java 11, Spring 2.6.6, OpenFeign 3.1.2, MongoDB, VS Code.


### 📸 Prints da chamada ao microserviço de chamados:

Requisição de chamado COM equipamento linkado:

![image](https://user-images.githubusercontent.com/55204419/168143088-43459269-c370-45e9-9a8a-3e83c1dee99c.png)

Requisição de chamado SEM equipamento linkado:

![image](https://user-images.githubusercontent.com/55204419/168142956-6c62bfc9-f1a6-4916-bd4f-6faa660e2328.png)
